#!/bin/bash

#
# Universidade Federal do Rio de Janeiro
# Escola Politécnica
# Projeto Final de Graduação
# Ambiente de Teste para Filtros Adaptativos
# Pedro Angelo Medeiros Fonini
# Orientador: Markus Lima
#

# This script generates the filter200Hz.h file that is included from Stream.cpp

mkdir -p ../../src/autogen

cat >../../src/autogen/filter200Hz.h <<EOF
// AUTOGENERATED FILE
/*
 * This file holds the DFT of a length-65 impulse response that filters out the
 * 0~200Hz range (roughly), assuming that the sampling frequency is 11025Hz.
 */
/*
 * To generate this file, use the script codegen/filter200Hz/mkheader.sh
 */
#include "../Stream.h"
static const double filter200Hz_re_array[256] = {
EOF

octave -q filter200Hz.m re >>../../src/autogen/filter200Hz.h

cat >>../../src/autogen/filter200Hz.h <<EOF
};
static const double filter200Hz_im_array[256] = {
EOF

octave -q filter200Hz.m im >>../../src/autogen/filter200Hz.h

cat >>../../src/autogen/filter200Hz.h <<EOF
};
const Stream::container_t Stream::filter200Hz_re(
    filter200Hz_re_array, filter200Hz_re_array + 256
);
const Stream::container_t Stream::filter200Hz_im(
    filter200Hz_im_array, filter200Hz_im_array + 256
);
EOF
