Ambiente de Teste para Filtros Adaptativos: Signal Class Reference
Signal Class Reference
A time- or frequency-domain signal.
#include <Signal.h>
Classes
class DFTDriver
A class for providing discrete Fourier transform capabilities.
Public Types
enum delay_t { MS, SAMPLE }
This is a type for specifying whether a time interval is given in milliseconds or in samples.
typedef float sample_t
The type for holding each signal sample.
typedef unsigned long index_t
The type for holding each signal sample index.
typedef std::vector< sample_t > container_t
The type for holding the whole vector of signal samples.
Public Member Functions
Signal ()
Constructs an empty signal.
Signal (const std::string &filename)
Constructs a signal from an audio file.
Signal (const Signal &other)
Copy-constructor. Constructs a signal as a copy of another.
~Signal ()
Frees memory used.
const sample_t * array () const
Returns a pointer to the first sample.
index_t samples () const
Number of samples.
int samplerate () const
Sample rate in samples per second.
sample_t & operator[] (index_t index)
Returns a sample.
const sample_t & operator[] (index_t index) const
Returns a "read-only" sample.
void set_size (index_t n)
Changes the number of samples.
void set_samplerate (int sr)
Re-samples the signal.
void delay (delay_t t, unsigned long d)
Delays the signal in time.
void gain (double g)
Applies gain g to the signal.
sample_t l_inf_norm ()
Gets the -norm of the signal.
void normalize ()
Normalize the signal according to its -norm.
Signal & operator+= (Signal other)
Adds the other signal to the caller.
void filter (Signal imp_resp)
Convolves the sinal with an impulse response.
void play (bool sleep=true)
Makes PortAudio playback the audio signal.
Public Attributes
index_t counter
general-purpose variable for external use.
Static Public Attributes
static DFTDriver dft
Single instance of the DFTDriver class.
Private Attributes
container_t data
Holds the signal samples.
int srate
Signal sample rate in Hertz.
Detailed Description
A time- or frequency-domain signal.
Holds data and provides routines for dealing with time-domain and frequency-domain signals. Currently, all Signals are an array of single-precision floating-point samples. Signals are aware of their sample rates.
Todo:
Implement "stream" signals, to provide real-time processing.
Definition at line 114 of file Signal.h.
Member Typedef Documentation
typedef std::vector<sample_t> Signal::container_t
The type for holding the whole vector of signal samples.
Definition at line 125 of file Signal.h.
typedef unsigned long Signal::index_t
The type for holding each signal sample index.
Definition at line 122 of file Signal.h.
typedef float Signal::sample_t
The type for holding each signal sample.
Definition at line 119 of file Signal.h.
Member Enumeration Documentation
enum Signal::delay_t
This is a type for specifying whether a time interval is given in milliseconds or in samples.
Enumerator
MS
Time interval given in milliseconds.
SAMPLE
Time interval given in samples.
Definition at line 129 of file Signal.h.
Constructor & Destructor Documentation
Signal::Signal () inline
Constructs an empty signal.
Initializes the signal with no meta-data and no samples. The user needs to specify the sample rate and create samples before using the signal.
Definition at line 139 of file Signal.h.
Signal::Signal (const std::string & filename)
Constructs a signal from an audio file.
Constructs a signal getting the signal data from an audio file. This is done using the libsndfile library. The filetypes supported are listed here. WAV is supported, but MP3 is not.
If the given file is stereo, or otherwise multi-channel, just the first channel will be read. (On stereo audio files, this is the left channel.)
The sample rate is extracted from the file's meta-data info.
Parameters
[in] filename Audio file name.
Exceptions
FileError if file openening/reading fails.
Definition at line 45 of file Signal.cpp.
References data, samples(), set_size(), and srate.
Signal::Signal (const Signal & other) inline
Copy-constructor. Constructs a signal as a copy of another.
Constructs a signal as a copy of another one. If this signal is not empty, we destroy it.
Parameters
[in] other The signal to be copied from.
Definition at line 151 of file Signal.h.
Signal::~Signal () inline
Frees memory used.
Free the pointer to the array of samples.
Definition at line 158 of file Signal.h.
Member Function Documentation
const sample_t* Signal::array () const inline
Returns a pointer to the first sample.
Sometimes needed for performance reasons. Shouldn't be used to modify the samples.
Returns
a pointer to the first element of a contiguous region of memory that holds the samples.
Definition at line 168 of file Signal.h.
References data.
void Signal::delay (delay_t t, unsigned long d)
Delays the signal in time.
Adds zeroed samples at the beginning of the signal.
If we try do delay a signal by milliseconds, but the signal has no associated sample rate, a warning is emitted, and nothing is done. No exception is thrown.
Parameters
[in] t A delay type element.
[in] d The time interval to be delayed, given in the units specified by t.
Definition at line 88 of file Signal.cpp.
References data, MS, samples(), set_size(), and srate.
Referenced by main().
void Signal::filter (Signal imp_resp)
Convolves the sinal with an impulse response.
Convolves the signal with the given finite impulse response (FIR).
The algorthm used is the "overlap-and-add", and we use the FFT implemented in the DFTDriver class to compute each step. We try to do it using the least possible number of DFTs.
Parameters
[in] imp_resp The filter impulse response to be convolved with.
See Also
DFTDriver::operator()
Definition at line 115 of file Signal.cpp.
References data, dft, Signal::DFTDriver::INVERSE, samples(), set_samplerate(), set_size(), srate, and Signal::DFTDriver::tblsize.
Referenced by main().
void Signal::gain (double g)
Applies gain g to the signal.
This can be useful, for example, to make sure that the signal is within the range.
Parameters
[in] g The signal gain to be applied.
Definition at line 394 of file Signal.cpp.
References data.
Referenced by normalize().
Signal::sample_t Signal::l_inf_norm ()
Gets the -norm of the signal.
Take the signal's infinity-norm, which is the maximum absolute value of all the samples of the signal.
Returns
the -norm of the signal.
Definition at line 406 of file Signal.cpp.
References data.
Referenced by normalize().
void Signal::normalize () inline
Normalize the signal according to its -norm.
Divide the signal by a constant so that the maximum absolute value of its samples is .
Definition at line 231 of file Signal.h.
References gain(), and l_inf_norm().
Referenced by main().
Signal & Signal::operator+= (Signal other)
Adds the other signal to the caller.
First, we re-sample other into a new temporary signal. Then we increase the caller's size if needed, and finally add the signals sample-by-sample.
Parameters
[in] other The signal to be added to the caller.
Returns
a reference to this signal, already added to the other.
Definition at line 379 of file Signal.cpp.
References data, samples(), set_samplerate(), set_size(), and srate.
sample_t& Signal::operator[] (index_t index) inline
Returns a sample.
Gets a sample of the signal. For performance reasons, this method does not check that the given index is valid.
Parameters
[in] index The index of the desired sample. Signal indexes are zero-based.
Returns
a reference to the sample.
Definition at line 195 of file Signal.h.
References data.
const sample_t& Signal::operator[] (index_t index) const inline
Returns a "read-only" sample.
Just like the "read-write" version, but returns a const reference to a sample.
Parameters
[in] index The index of the desired sample. Signal indexes are zero-based.
Returns
a const reference to the sample.
Definition at line 207 of file Signal.h.
References data.
void Signal::play (bool sleep = true)
Makes PortAudio playback the audio signal.
Creates a PortAudio stream for audio playback of the signal content. If sleep is true, we wait for the playback to end before returning. (If it's false, the function returns, while playback goes on in the background.)
Parameters
[in] sleep If set to true, the method will only return when the playback ends (that is, when the end of the signal is reached). Otherwise, it returns imediatly, and the playback goes on in the background.
Exceptions
std::runtime_error if any of the PortAudio steps fail (check the source code)
See Also
callback
Definition at line 298 of file Signal.cpp.
References callback(), counter, samples(), and srate.
Referenced by playsig().
int Signal::samplerate () const inline
Sample rate in samples per second.
Returns
the number of samples per second that should be used when playing back the signal.
Definition at line 181 of file Signal.h.
References srate.
index_t Signal::samples () const inline
Number of samples.
Returns
the number of elements inside the vector of samples.
Definition at line 174 of file Signal.h.
References data.
Referenced by delay(), filter(), operator+=(), play(), set_samplerate(), and Signal().
void Signal::set_samplerate (int sr)
Re-samples the signal.
Changes the sample rate of the signal. The way it is done, this is equivalent to reconstructing the time-domain signal by linear interpolation, and then re-sampling the continuous-time reconstructed signal at the new sample rate.
Parameters
[in] sr The new sample rate in Hertz.
See Also
srate
Definition at line 356 of file Signal.cpp.
References data, samples(), and srate.
Referenced by filter(), and operator+=().
void Signal::set_size (index_t n) inline
Changes the number of samples.
Changes the signal length. Allocates more space if we are growing the signal, and deletes the last samples if we are shrinking it. Also initializes any new samples to zero.
Parameters
[in] n The desired signal length.
See Also
container_t::resize()
Definition at line 219 of file Signal.h.
References data.
Referenced by delay(), filter(), main(), operator+=(), and Signal().
Member Data Documentation
index_t Signal::counter
general-purpose variable for external use.
Definition at line 183 of file Signal.h.
Referenced by play().
container_t Signal::data private
Holds the signal samples.
Definition at line 463 of file Signal.h.
Referenced by array(), delay(), filter(), gain(), l_inf_norm(), operator+=(), operator[](), samples(), set_samplerate(), set_size(), and Signal().
Signal::DFTDriver Signal::dft static
Single instance of the DFTDriver class.
Definition at line 460 of file Signal.h.
Referenced by filter().
int Signal::srate private
Signal sample rate in Hertz.
Definition at line 464 of file Signal.h.
Referenced by delay(), filter(), operator+=(), play(), samplerate(), set_samplerate(), and Signal().
The documentation for this class was generated from the following files:
Signal.h (v0.1-1-g41ddbc8)
main.cpp (v0.1-1-g41ddbc8)
Signal.cpp (v0.1-1-g41ddbc8)