Ambiente de Teste para Filtros Adaptativos: Signal::DFTDriver Class Reference
Signal::DFTDriver Class Reference
A class for providing discrete Fourier transform capabilities.
#include <Signal.h>
Public Types
enum dir_t { DIRECT, INVERSE }
Public Member Functions
DFTDriver ()
Constructor for an object that computes DFTs.
void operator() (container_t &re, container_t &im, dir_t direction=DIRECT)
Used to perform the actual computation of the DFT.
Static Public Member Functions
static std::vector< double > initialize_costbl ()
Initializes the table of cosines.
static std::vector< double > initialize_sintbl ()
Initializes the table of sines.
Static Public Attributes
static const unsigned tblbits = 14
Number of bits for the index of the table of sines and cosines.
static const size_t tblsize = 16384
Number of entries in the tables of sines and cosines.
Private Member Functions
double Wre (unsigned k)
Easy access to the table of cosines.
double Wim (unsigned k)
Easy access to the table of sines.
Static Private Member Functions
template<typename T >
static T br (T x, int bits)
Bit-reverse.
Private Attributes
unsigned bits
Number of bits for the current FFT computation.
Static Private Attributes
static const std::vector< double > sintbl
Table of sines.
static const std::vector< double > costbl
Table of cosines.
Detailed Description
A class for providing discrete Fourier transform capabilities.
This class implements the radix-2 FFT algorithm used in the Signal::filter() method.
Usage:
Signal::DFTDriver dft;
Signal::container_t real, imag;
// initialize the real and imaginary parts of a complex time-domain
// signal
dft(real, imag); // performs in-place FFT
// now, work with the real and imaginary parts of the
// frequency-domain version of the signal
dft(real, imag, Signal::DFTDriver::INVERSE); // inverse in-place fft
// now, we can work again with the time-domain complex signal
Definition at line 191 of file Signal.h.
Member Enumeration Documentation
enum Signal::DFTDriver::dir_t
This is a type for specifying whether we should perform a direct or inverse FFT.
Enumerator
DIRECT
Perform direct FFT.
INVERSE
Perform inverse FFT.
Definition at line 336 of file Signal.h.
Constructor & Destructor Documentation
Signal::DFTDriver::DFTDriver () inline
Constructor for an object that computes DFTs.
Does nothing at all.
Definition at line 372 of file Signal.h.
Member Function Documentation
template<typename T > static T Signal::DFTDriver::br (T x, int bits) inline static private
Bit-reverse.
Returns the bit-reversed version of the parameter x. Assumes x is bits-bit wide, and ignore any bits with more significance than that.
This function assumes that the number of bits in one char is 8, and that bitshifting is zero-padded, and not circular.
Template Parameters
T The type of the parameter x. It must be an unsigned integer type.
Parameters
[in] x The bits-bit unsigned integer to be bit-reversed.
[in] bits The number of bits of the integer x.
Returns
the unsigned integer x, bit-reversed.
Definition at line 217 of file Signal.h.
Referenced by operator()().
static std::vector<double> Signal::DFTDriver::initialize_costbl () inline static
Initializes the table of cosines.
Computes a table of cosines that will be handed to the costbl member.
See Also
initialize_sintbl
costbl
Definition at line 349 of file Signal.h.
References TAU, and tblsize.
static std::vector<double> Signal::DFTDriver::initialize_sintbl () inline static
Initializes the table of sines.
See Also
initialize_costbl
sintbl
Definition at line 361 of file Signal.h.
References TAU, and tblsize.
void Signal::DFTDriver::operator() (container_t & re, container_t & im, dir_t direction = DIRECT)
Used to perform the actual computation of the DFT.
Implements the radix-2 time-decimation FFT algorithm. The computation happens in-place, which means that the re and im parameters are substituted by their new versions.
Of course, the re and im vectors must be of the same size. This size must be a power of two not greater than tblsize.
Refer to the DFTDriver class documentation for usage details.
Exceptions
std::runtime_error if any of the above conditions aren't met.
Parameters
[in,out] re Real part of the compelx signal on which the FFT will act.
[in,out] im Imaginary part.
[in] direction Wether this is a direct or inverse DFT.
Definition at line 446 of file Signal.cpp.
References bits, br(), DIRECT, INVERSE, tblsize, Wim(), and Wre().
double Signal::DFTDriver::Wim (unsigned k) inline private
Easy access to the table of sines.
Parameters
[in] k Same as in Wre.
Returns
See Also
sintbl
Wre
Definition at line 310 of file Signal.h.
References bits, sintbl, and tblbits.
Referenced by operator()().
double Signal::DFTDriver::Wre (unsigned k) inline private
Easy access to the table of cosines.
This function is aware of the number of bits of the current FFT, and makes it easy to get the cosine of , using the pre-computed table of cosines.
Parameters
[in] k An integer in the range .
Returns
, where is shorthand for .
See Also
costbl
Wim
Definition at line 298 of file Signal.h.
References bits, costbl, and tblbits.
Referenced by operator()().
Member Data Documentation
unsigned Signal::DFTDriver::bits private
Number of bits for the current FFT computation.
Always assume this is uninitialized, and all methods that use it should initialize it themselves.
Definition at line 198 of file Signal.h.
Referenced by operator()(), Wim(), and Wre().
const std::vector< double > Signal::DFTDriver::costbl static private
Initial value:
=
        Signal::DFTDriver::initialize_costbl()
Table of cosines.
See Also
sintbl
Definition at line 393 of file Signal.h.
Referenced by Wre().
const std::vector< double > Signal::DFTDriver::sintbl static private
Initial value:
=
        Signal::DFTDriver::initialize_sintbl()
Table of sines.
Holds the sines of , for in the range . Here, is shorthand for .
See Also
costbl
Definition at line 387 of file Signal.h.
Referenced by Wim().
const unsigned Signal::DFTDriver::tblbits = 14 static
Number of bits for the index of the table of sines and cosines.
We won't be able to perform an -bit dft if , so this should be big. Also, this must be equal to , but there's nothing in the source code that enforces it.
See Also
tblsize
Definition at line 323 of file Signal.h.
Referenced by Wim(), and Wre().
const size_t Signal::DFTDriver::tblsize = 16384 static
Number of entries in the tables of sines and cosines.
This must be equal to , but there's nothing in the source code that enforces it.
See Also
tblbits
Definition at line 332 of file Signal.h.
Referenced by Signal::filter(), initialize_costbl(), initialize_sintbl(), and operator()().
The documentation for this class was generated from the following files:
Signal.h (v0.1.1-17-gc9cc97d)
Signal.cpp (v0.1.1-17-gc9cc97d)