Ambiente de Teste para Filtros Adaptativos: Stream Class Reference
Stream Class Reference
Represents an input/output stream of audio samples.
#include <Stream.h>
Classes
struct sample_wrapper_t
A structured type for holding a single sample. Will be simplified later.
Public Types
typedef float sample_t
The type for holding each signal sample.
typedef unsigned long index_t
The type for holding each signal sample index.
typedef std::vector
< sample_wrapper_t > container_t
The type for holding the whole vector of signal samples.
Public Member Functions
sample_t read ()
Returns the next audio sample.
container_t::const_iterator get_last_n (index_t n)
Returns an "array" with the last n samples.
sample_t get_filtered_sample ()
Returns a sample from the stream echoed by the impulse response.
void write (sample_t s)
Writes an audio sample to the stream.
Stream ()
Initializes important values.
void echo (unsigned sleep=0)
Runs the stream with predefined scenario parameters.
void set_delay (unsigned msec)
Sets the delay parameter, given in miliseconds.
void set_filter (container_t h)
Sets the room impulse response.
void dump_state (const container_t speaker_buf) const
Used for debugging, together with simulate
void simulate ()
Simulates a PortAudio session, used for debugging.
Static Public Attributes
static const unsigned samplerate = 11025
The stream's rate in samples per second.
static const size_t buf_size = 8*samplerate
The number of data samples held internally be the stream structure.
Private Member Functions
sample_t & operator[] (index_t index)
Returns a sample.
const sample_t & operator[] (index_t index) const
Returns a "read-only" sample.
Private Attributes
index_t delay_samples
The delay of the communication channel, measured in samples.
container_t data
The container for holding the internal memory of the data structure.
container_t::iterator write_ptr
An iterator to the next location to be written on the stream.
container_t::const_iterator read_ptr
An iterator to the next location to be read from the stream.
const container_t::const_iterator semantic_end
An iterator to the middle of the vector data
container_t imp_resp
Detailed Description
Represents an input/output stream of audio samples.
Holds data and provides routines for dealing with streams that represent communication systems with echo. Currently, all Streams are implemented as a circular array of single-precision floating-point samples. Streams are aware of their sample rates.
The stream uses the circular array as an internal memory. The array holds 2 * buf_size audio samples. When we tell the stream to start running, the write pointer (write_ptr) points to the first element of this array. Everytime we receive a new audio sample from the microphone (through PortAudio), we write it to the location pointed to by the write pointer, and also to the location pointed to by write_ptr + buf_size. This way, we will always have a doubled vector of samples. When the write pointer reaches the middle of the circular vector, that is, the buf_size+1-th element, it rewinds back to the first element. A useful diagram is presented in the description for the data element.
Whenever we need a new audio sample to playback (which happens whenever we receive a new sample – the audio input and output are coerent), we read it from the the location pointed to by the read pointer (read_ptr), and increment the read pointer (rewinding it if necessary).
By calling the set_delay() method, we place the read pointer at a specified number of samples behind the write pointer, so that running the stream makes it echo everything it "hears".
The data member of the class holds the circular array.
semantic_end is a pointer to the "`buf_size+1`-th element". For looping through "all" the samples, we should do for (iterator = data.begin(); iterator != semantic_end; ++iterator) {}
For writing samples in the manner specified above in second paragraph, we use the write() routine.
Although there is an analogous read() routine, if we want the audio to pass through the room impulse response, we use the get_filtered_sample() method instead. It modifies the read pointer in the same way as read() does.
Definition at line 64 of file Stream.h.
Member Typedef Documentation
typedef std::vector<sample_wrapper_t> Stream::container_t
The type for holding the whole vector of signal samples.
Definition at line 83 of file Stream.h.
typedef unsigned long Stream::index_t
The type for holding each signal sample index.
Definition at line 72 of file Stream.h.
typedef float Stream::sample_t
The type for holding each signal sample.
Definition at line 69 of file Stream.h.
Constructor & Destructor Documentation
Stream::Stream () inline
Initializes important values.
Constructs a scenario in which there is no delay, and the impulse response has one sample of value zero. Also acquires memory for the data structure.
See Also
data
read
Definition at line 203 of file Stream.h.
References buf_size, and samplerate.
Member Function Documentation
void Stream::dump_state (const container_t speaker_buf) const
Used for debugging, together with simulate
This function is called be simulate() to print to the screen the current state of the simulated environment. It prints the internal state of the Stream object and the samples that have been written to the output.
Parameters
[in] speaker_buf A vector with the samples that have been sent to the output (speaker).
See Also
simulate
Definition at line 176 of file Stream.cpp.
References data.
Referenced by simulate().
void Stream::echo (unsigned sleep = 0)
Runs the stream with predefined scenario parameters.
This is one of the main methods in the Stream class. It runs the stream, simulating a communications environment in which the user listens to echoes of his own voice.
Creates a PortAudio session for audio I/O. If sleep is not zero, we only run the stream for the time duration specified in miliseconds. If it's zero, we run the stream until something kills the process.
To use this method, you should first set the scenario parameters using the methods set_filter and set_delay.
Parameters
[in] sleep The duration, in miliseconds, in which to run the stream.
Exceptions
std::runtime_error if any of the PortAudio steps fail (check the source code)
See Also
Stream
stream_callback
Definition at line 104 of file Stream.cpp.
References samplerate, set_delay(), and stream_callback().
Referenced by main().
sample_t Stream::get_filtered_sample () inline
Returns a sample from the stream echoed by the impulse response.
Just like read(), but returns a sample from the signal that was convolved with the room impulse response.
Returns
a sample of the echoed signal
See Also
read
read_ptr
Definition at line 163 of file Stream.h.
References get_last_n(), and imp_resp.
Referenced by stream_callback().
container_t::const_iterator Stream::get_last_n (index_t n) inline
Returns an "array" with the last n samples.
Makes a pointer (actually, an iterator) to the n-th pointer behind read_ptr. Handles the case in which the range crosses the end of the circular structure. That is, for any valid value of read_ptr, this function can be called with any . A valid read_ptr is one such that read_ptr - data.begin() is in the range .
Parameters
[in] n The size, in samples, of the "array" that is returned
Returns
an iterator pointing to the last n samples.
See Also
data
Definition at line 143 of file Stream.h.
References buf_size, data, read_ptr, and semantic_end.
Referenced by get_filtered_sample().
sample_t& Stream::operator[] (index_t index) inline private
Returns a sample.
Gets a sample of the signal. Used only in debugging, when we want a snapshot of the stream internal data.
Parameters
[in] index The index of the desired sample.
Returns
a reference to the sample.
Definition at line 331 of file Stream.h.
References data.
const sample_t& Stream::operator[] (index_t index) const inline private
Returns a "read-only" sample.
Just like the "read-write" version, but returns a const reference to a sample.
Parameters
[in] index The index of the desired sample.
Returns
a const reference to the sample.
Definition at line 347 of file Stream.h.
References data.
sample_t Stream::read () inline
Returns the next audio sample.
Reads the audio sample pointed to by read_ptr and makes the pointer indicate the next sample. Handles the case in which the pointer must be rewinded, because the data structure is circular.
Returns
the next audio sample in line
See Also
data
write
Definition at line 118 of file Stream.h.
References data, read_ptr, and semantic_end.
void Stream::set_delay (unsigned msec) inline
Sets the delay parameter, given in miliseconds.
Calculates how many samples are equivalent to the specified delay, and moves the read pointer to that many samples behind the write pointer.
This function doesn't check whether the given delay is valid, so that the application must be sure that the delay msec is such that
Parameters
[in] msec The time delay, specified in miliseconds
See Also
delay_samples
read_ptr
Definition at line 232 of file Stream.h.
References buf_size, data, delay_samples, read_ptr, samplerate, and write_ptr.
Referenced by echo(), main(), and simulate().
void Stream::set_filter (container_t h)
Sets the room impulse response.
This function just sets the internal copy of the room impulse response (RIR) samples to be equal to the one specified.
Parameters
[in] h A vector containing the RIR samples
Definition at line 161 of file Stream.cpp.
References imp_resp.
Referenced by main().
void Stream::simulate ()
Simulates a PortAudio session, used for debugging.
This function simulates the PortAudio functioning by calling the callback function some four times, each time providing it with different in/out buffers.
See Also
dump_state
Definition at line 198 of file Stream.cpp.
References dump_state(), set_delay(), and stream_callback().
Referenced by main().
void Stream::write (sample_t s) inline
Writes an audio sample to the stream.
Writes a sample to the data structure so that it can be later read by read() or get_last_n(). Writes it twice (one in each copy of the data structure), so that the list is always "doubled" to make it look "circular".
Handles the case in which the pointer must be rewinded.
Parameters
[in] s The value of sample to be written to the stream's internal memory
See Also
data
read
Definition at line 186 of file Stream.h.
References buf_size, data, semantic_end, and write_ptr.
Referenced by stream_callback().
Member Data Documentation
const size_t Stream::buf_size = 8*samplerate static
The number of data samples held internally be the stream structure.
The actual size of the vector used to hold the samples is 2*samplerate, in order to make the data structure "look" circular.
Definition at line 94 of file Stream.h.
Referenced by get_last_n(), set_delay(), Stream(), and write().
container_t Stream::data private
The container for holding the internal memory of the data structure.
A C++ vector that holds the internal memory representation of the stream. The vector contains two copies of each audio sample. It can be though of as a concatenation of two identical vectors, each equal to a "circular buffer" of size buf_size that is used to keep track of the stream's state.
data.begin()                            semantic_end          data.end()
     |                                        |                     |
   --------------------------------------------------------------------
   | 0 | 1 | ... | buf_size - 1 | buf_size | ... | 2*buf_size - 1 |   |
   --------------------------------------------------------------------
                                 from here on, the vector contains just
                                 a repetition of the first `buf_size' samples
Todo:
esse digrama devia ser xfig, e no ascii-art
See Also
read
get_last_n
write
Stream
Definition at line 279 of file Stream.h.
Referenced by dump_state(), get_last_n(), operator[](), read(), set_delay(), and write().
index_t Stream::delay_samples private
The delay of the communication channel, measured in samples.
Definition at line 254 of file Stream.h.
Referenced by set_delay().
container_t Stream::imp_resp private
Definition at line 320 of file Stream.h.
Referenced by get_filtered_sample(), and set_filter().
container_t::const_iterator Stream::read_ptr private
An iterator to the next location to be read from the stream.
A sample should be read from the stream like:
sample = *read_ptr++;
if (read_ptr == semantic_end) read_ptr = data.begin();
See Also
read
semantic_end
write_ptr
Definition at line 310 of file Stream.h.
Referenced by get_last_n(), read(), and set_delay().
const unsigned Stream::samplerate = 11025 static
The stream's rate in samples per second.
Definition at line 87 of file Stream.h.
Referenced by echo(), set_delay(), and Stream().
const container_t::const_iterator Stream::semantic_end private
An iterator to the middle of the vector data
Points to the first repeating element in data. See the diagram provided in the data element description and the explanation in the Stream class description.
Definition at line 318 of file Stream.h.
Referenced by get_last_n(), read(), and write().
container_t::iterator Stream::write_ptr private
An iterator to the next location to be written on the stream.
A sample should be written to the stream like:
*write_ptr = sample;
*(write_ptr++ + buf_size) = sample;
if (write_ptr == semantic_end) write_ptr = data.begin();
It is important to write the sample to both locations (write_ptr and write_ptr + buf_size) in case we read from the stream through functions like get_last_n().
See Also
write
semantic_end
read_ptr
Definition at line 297 of file Stream.h.
Referenced by set_delay(), and write().
The documentation for this class was generated from the following files:
Stream.h (v0.1.1-14-ga4f2141)
Stream.cpp (v0.1.1-14-ga4f2141)