Ambiente de Teste para Filtros Adaptativos: main.cpp File Reference
main.cpp File Reference
(v0.1-2-g9e18d32)
#include "Signal.h"
#include <cstring>
#include <libgen.h>
Macros
#define ATFA_DIR
Macro for getting the path to the project directory from cmake.
Functions
void portaudio_init (bool list_devices=false)
Initialize PortAudio.
void portaudio_end ()
Close PortAudio.
void playsig (Signal s)
Playback signal.
int main (int argc, char *argv[])
main() function.
Variables
char static_filename [] = __FILE__
char static_dirname [] = __FILE__
char static_projdirname [] = __FILE__
Detailed Description
Holds the main() function and other routines.
Author
Pedro Angelo Medeiros Fonini
Definition in file main.cpp.
Macro Definition Documentation
#define ATFA_DIR
Value:
(static_cast<const char *>(\
        std::strcpy(static_dirname, dirname(static_filename)), \
        std::strcpy(static_filename, __FILE__), \
        std::strcpy(static_projdirname, dirname(static_dirname)), \
        static_projdirname \
    ))
Macro for getting the path to the project directory from cmake.
Should be passed from CMakeLists.txt, but if it's not, we try to deduce it from the __FILE__ macro
Definition at line 35 of file main.cpp.
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
main() function.
No command-line parameters.
This function:
Prints version info
Creates two Signals, sound_me and sound_other from two input files.
Delays the second.
Creates an impulse response.
Filters sound_me according to the impulse response and adds it to the second, delayed.
Initializes a PortAudio session, plays the resulting sound, and closes PortAudio.
Parameters
[in] argc argument count (unused)
[in] argv argument values (unused)
Returns
0 if no errors
Definition at line 144 of file main.cpp.
References ATFA_DIR, Signal::delay(), Signal::filter(), Signal::MS, Signal::normalize(), playsig(), and Signal::set_size().
void playsig (Signal s)
Playback signal.
Wrapper function for Signal::play that handles PortAudio.
Definition at line 119 of file main.cpp.
References Signal::play(), portaudio_end(), and portaudio_init().
Referenced by main().
void portaudio_end ()
Close PortAudio.
Ends a PortAudio session.
Exceptions
std::runtime_error if PortAudio closing fails.
See Also
portaudio_init()
Definition at line 106 of file main.cpp.
Referenced by playsig().
void portaudio_init (bool list_devices = false)
Initialize PortAudio.
Initializes a PortAudio session. Also prints out a list of available devices that PortAudio sees., if requested.
Parameters
[in] list_devices Whether or not to print the device list.
Exceptions
std::runtime_error if PortAudio initialization fails.
See Also
portaudio_end()
Definition at line 64 of file main.cpp.
Referenced by playsig().
Variable Documentation
char static_dirname[] = __FILE__
Definition at line 27 of file main.cpp.
char static_filename[] = __FILE__
Definition at line 26 of file main.cpp.
char static_projdirname[] = __FILE__
Definition at line 28 of file main.cpp.