Ambiente de Teste para Filtros Adaptativos: Stream.cpp File Reference
Stream.cpp File Reference
(v0.2)
#include <portaudio.h>
#include <iostream>
#include "Stream.h"
Functions
static int stream_callback (const void *in_buf, void *out_buf, unsigned long frames_per_buf, const PaStreamCallbackTimeInfo *time_info, PaStreamCallbackFlags status_flags, void *user_data)
Callback function for dealing with PortAudio.
Detailed Description
Holds the implementation of the Stream class.
Author
Pedro Angelo Medeiros Fonini
Definition in file Stream.cpp.
Function Documentation
static int stream_callback (const void * in_buf, void * out_buf, unsigned long frames_per_buf, const PaStreamCallbackTimeInfo * time_info, PaStreamCallbackFlags status_flags, void * user_data) static
Callback function for dealing with PortAudio.
See the description for the signal_callback() function, in the Signal.cpp file for information on how this function accomplishes audio I/O, together with PortAudio.
Parameters
[in] in_buf Pointer to a buffer of samples retrieved from an input audio device. We read these samples into the stream, at the location pointed to by the Stream's Stream::write_ptr.
[out] out_buf Pointer to a buffer where the callback function will store samples to be given to an output audio device. We write to this location the samples we get from the stream through the Stream::read_ptr pointer.
[in] frames_per_buf Number of samples we will write/read to/from the PortAudio buffers. This is actually the number of frames, which in turn is equal to number of samples because we're working with mono-channel signals.
[in] time_info PortAudio time information. (unused)
[in] status_flags PortAudio status flags. (unused)
[in,out] user_data Pointer to an arbitrary data-holder passed to the stream open function. In this case, this is a pointer to the Stream object.
See Also
Stream::echo
Definition at line 61 of file Stream.cpp.
References Stream::get_filtered_sample(), and Stream::write().
Referenced by Stream::echo(), and Stream::simulate().